#!/usr/bin/env python3
"""Render and audit all runtime projections from the canonical platform.env."""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import importlib.util
import ipaddress
import json
import os
import re
import sys
import uuid
from contextlib import contextmanager
from pathlib import Path
from typing import Any
from urllib.parse import quote

import yaml

ROOT = Path("/opt/mte-platform")
SECRET_ROOT = Path("/root/.config/mte-secrets")
SOURCE = SECRET_ROOT / "platform.env"
MANIFEST = SECRET_ROOT / "projections-manifest.json"
LOCK = SECRET_ROOT / ".platform-env.lock"
CONFIG_SOURCE = ROOT / "templates/platform.json"
CONFIG = ROOT / "config/platform.json"
SERVICE_ROOT = SECRET_ROOT / "services"
PROFILE_SOURCE = ROOT / "templates/profiles/profiles.yaml"
PROFILE_RUNTIME = ROOT / "runtime/profiles/profiles.yaml"
COMPOSE_SEED_SOURCE = ROOT / "templates/compose-seeds.lock.json"
PLATFORM_LOCK_SOURCE = ROOT / "templates/platform.lock.yaml"
PUBLIC_URLS = ROOT / "config/public-urls.json"
DATA_CONTENT_PLANE = ROOT / "config/data-content-plane.json"
CLOUDFLARE_APPS = SECRET_ROOT / "cloudflare/apps.json"
CLOUDFLARE_API_ENV = SECRET_ROOT / "cloudflare/api.env"
CLOUDFLARE_TUNNEL_TOKEN = SECRET_ROOT / "cloudflare/tunnel-token"
CLOUDFLARE_ACCESS_TOKEN = SECRET_ROOT / "cloudflare/access-service-token.json"
GENERATOR_VERSION = "mte-config-renderer/v1"
ENV_PATTERN = re.compile(r"\$\{([A-Z][A-Z0-9_]*)(?:(:-|:\?)([^}]*))?\}")
SENSITIVE_KEY_PATTERN = re.compile(
    r"(?:PASSWORD|PASSWD|SECRET|TOKEN|API_KEY|PRIVATE_KEY|ENCRYPT|JWT|SALT|"
    r"COOKIE|CREDENTIAL|AUTH|WEBHOOK|CONNECTION_STRING)",
    re.IGNORECASE,
)
MUTABLE_KEY_PATTERN = re.compile(
    r"(?:PORT|URL|URI|HOST|DOMAIN|ENDPOINT|IMAGE|VERSION|CPU|MEMORY|LIMIT|"
    r"CONCURRENCY|WORKERS|POOL|ENABLED|MODE)$",
    re.IGNORECASE,
)
GENERATED_PREFIX = "# GENERATED by mte-config-renderer; DO NOT EDIT; "
PUBLIC_URL_PROJECTIONS = {
    "BASEROW_PUBLIC_URL": "BASEROW_SUBDOMAIN",
    "WIKIJS_SITE_URL": "WIKIJS_SUBDOMAIN",
    "MATHESAR_PUBLIC_URL": "MATHESAR_SUBDOMAIN",
    "POSTGREST_PUBLIC_URL": "POSTGREST_SUBDOMAIN",
    "MEMOS_PUBLIC_URL": "MEMOS_SUBDOMAIN",
    "NOCODB_PUBLIC_URL": "NOCODB_SUBDOMAIN",
    "MATTERMOST_SITE_URL": "MATTERMOST_SUBDOMAIN",
    "AP_FRONTEND_URL": "ACTIVEPIECES_SUBDOMAIN",
    "SEARXNG_BASE_URL": "SEARXNG_SUBDOMAIN",
}
DERIVED_VALUE_KEYS = {
    *PUBLIC_URL_PROJECTIONS,
    "AP_REDIS_URL",
    "BASEROW_DATABASE_URL",
    "BASEROW_REDIS_URL",
    "MATHESAR_DOMAIN_NAME",
    "MATHESAR_ALLOWED_HOSTS",
    "MEMOS_DSN",
    "MEMOS_MCP_URL",
    "NOCODB_META_DSN",
    "FIRECRAWL_REDIS_URL",
    "SEARXNG_VALKEY_URL",
}
NOTION_BOOTSTRAP_ID_KEYS = {
    "NOTION_DOCUMENTS_PAGE_ID",
    "NOTION_TABLE_DATABASE_ID",
    "NOTION_TABLE_DATA_SOURCE_ID",
    "NOTION_WORKSPACE_ID",
    "NOTION_BOT_ID",
}
NOTION_TOKEN_IMPORT_PRIORITY = (
    "PRIN7R_NOTION_TOKEN",
    "PRIN7R_NOTION_API_KEY",
    "NOTION_TOKEN",
)
REVIEWED_CANONICAL_VALUE_MIGRATIONS = {
    "TOOLHIVE_MEMORY_LIMIT": ("384m", "1024m"),
    "MTE_TOOLHIVE_TOOL_RUNTIME_IMAGE": (
        "docker:28-dind-rootless@sha256:7c3e797187e43738220462658f4586572cbd3bf009f728b21e34d9c5c06ce431",
        "docker:28-dind@sha256:9a06753d2401cd049b34cd27dbbc3e0db717d4c1db7bc7f2efad1c187e00bf5a",
    ),
    "MTE_AGENT_GATEWAY_TOOLHIVE_CODEX_UPSTREAM": (
        "http://tool-runtime:19011",
        "http://toolhive:19011",
    ),
    "MTE_AGENT_GATEWAY_TOOLHIVE_CLAUDE_UPSTREAM": (
        "http://tool-runtime:19012",
        "http://toolhive:19012",
    ),
    "MTE_AGENT_GATEWAY_TOOLHIVE_PI_UPSTREAM": (
        "http://tool-runtime:19013",
        "http://toolhive:19013",
    ),
}
REVIEWED_CANONICAL_KEY_MIGRATIONS = {
    "MTE_TOOLHIVE_TOOLHIVE_ENV_DOCKER_HOST": (
        "tcp://tool-runtime:2375",
        "MTE_TOOLHIVE_TOOLHIVE_ENV_DOCKER_SOCKET",
        "/var/run/docker.sock",
    ),
}
# These PostgREST Compose inputs were introduced after the first server
# bootstrap.  Existing canonical sources may therefore legitimately lack
# them.  This explicit allowlist permits a fill-only upgrade from the reviewed
# Compose seed catalog without turning that bootstrap catalog into a general
# source of recurring mutations.
REVIEWED_COMPOSE_SEED_MIGRATIONS = {
    "MTE_POSTGREST_POSTGREST_ENV_PGRST_ADMIN_SERVER_PORT",
    "MTE_POSTGREST_POSTGREST_ENV_PGRST_DB_URI",
    "MTE_POSTGREST_POSTGREST_ENV_PGRST_OPENAPI_MODE",
    "MTE_POSTGREST_POSTGREST_ENV_PGRST_SERVER_PORT",
    "MTE_POSTGREST_POSTGREST_IMAGE",
    "MTE_POSTGREST_POSTGREST_PORT_1_MAPPING",
    "MTE_POSTGREST_POSTGREST_PORT_2_MAPPING",
    "POSTGREST_ANON_ROLE",
    "POSTGREST_API_AUDIENCE",
    "POSTGREST_CPU_LIMIT",
    "POSTGREST_DB_HOST",
    "POSTGREST_DB_LOGIN_ROLE",
    "POSTGREST_DB_PORT",
    "POSTGREST_DB_SSLMODE",
    "POSTGREST_MEMORY_LIMIT",
    "POSTGREST_PIDS_LIMIT",
}
REVIEWED_TOOLHIVE_COMPOSE_SEED_MIGRATIONS = {
    "MTE_TOOLHIVE_TOOLHIVE_ENV_DOCKER_SOCKET",
}
REVIEWED_ACTIVEPIECES_COMPOSE_SEED_MIGRATIONS = {
    "MTE_ACTIVEPIECES_WORKER_ENV_AP_FRONTEND_URL",
}
POST_RENDER_PROVISIONED_KEYS = {
    "DOKPLOY_API_TOKEN",
    "NINEROUTER_PROFILE_CODING_DAYTONA_CODEX_API_KEY",
    "NINEROUTER_PROFILE_CODING_DAYTONA_CLAUDE_API_KEY",
    "NINEROUTER_PROFILE_CODING_DAYTONA_PI_API_KEY",
    "BASEROW_PAPERCLIP_TOKEN",
    "BASEROW_PAPERCLIP_TOKEN_ID",
    "BASEROW_ACTIVEPIECES_TOKEN",
    "BASEROW_ACTIVEPIECES_TOKEN_ID",
    "POSTGREST_PAPERCLIP_TOKEN",
    "POSTGREST_ACTIVEPIECES_TOKEN",
    "NOCODB_API_TOKEN",
    "NOCODB_API_TOKEN_ID",
    "NOCODB_API_TOKEN_SHA256",
    "NOCODB_BASE_ID",
    "NOCODB_SOURCE_ID",
    "NOCODB_TABLE_ID",
    *NOTION_BOOTSTRAP_ID_KEYS,
    "BASEROW_MCP_ENDPOINT_KEY",
    "BASEROW_MCP_ENDPOINT_ID",
    "BASEROW_WORKSPACE_ID",
    "BASEROW_DATABASE_ID",
    "BASEROW_TABLE_ID",
    "WIKIJS_API_TOKEN",
    "WIKIJS_API_TOKEN_ID",
    "MEMOS_SERVICE_PAT",
    "MEMOS_SERVICE_PAT_NAME",
    "MATTERMOST_ALERT_WEBHOOK_URL",
}
COMPOSE_DERIVED_ENV_REFS = {
    ("activepieces", "AP_REDIS_URL"): "AP_REDIS_URL",
    ("baserow", "DATABASE_URL"): "BASEROW_DATABASE_URL",
    ("baserow", "REDIS_URL"): "BASEROW_REDIS_URL",
    ("memos", "MEMOS_DSN"): "MEMOS_DSN",
    (
        "memos",
        "MEMOS_ALLOW_PRIVATE_WEBHOOKS",
    ): "MEMOS_ALLOW_PRIVATE_WEBHOOKS_ENABLED",
    ("nocodb", "NC_DB"): "NOCODB_META_DSN",
}
OPTIONAL_EMPTY_KEYS = {
    # These integrations are intentionally disabled by an empty value until
    # an operator enables them. Presence is required for deterministic
    # projections, but an empty value is not configuration drift.
    "HERMES_TELEGRAM_BOT_TOKEN",
    "HERMES_TELEGRAM_ALLOWED_USERS",
    # Issued by the 9Router bootstrap after the first runtime render.  The
    # provision stage fills it and triggers the next canonical projection.
    "HERMES_LLM_API_KEY",
    # The Daytona control-plane creates its API key during the Daytona stage.
    # The indexed deploy re-renders immediately after that atomic mutation.
    "DAYTONA_API_KEY",
    # NocoDocs API is a licensed self-hosted Business feature. An empty value
    # keeps the target profile runnable but acceptance remains red until the
    # operator activates a reviewed license.
    "NOCODB_LICENSE_KEY",
}
# Values that identify an operator's infrastructure must never be invented by
# the renderer or committed as deployment defaults.  They are accepted only
# from the explicit bootstrap input (or an already-existing canonical source).
REQUIRED_OPERATOR_BOOTSTRAP_KEYS = {
    "MTE_SSH_TARGET",
    "MTE_OPERATOR_SSH_CIDRS",
    "MTE_EXCLUDED_HOST_1",
    "MTE_EXCLUDED_HOST_2",
    "PLATFORM_BASE_DOMAIN",
}

# The checked-in environment template describes only values owned by the
# operator. CLOUDFLARE_EMAIL/GLOBAL_API_KEY are local bootstrap credentials and
# are deliberately never persisted to the server-side canonical source. The
# remaining external values are imported fill-only and then consumed from the
# canonical source by runtime services and acceptance checks.
LOCAL_ONLY_OPERATOR_INPUT_KEYS = {
    "CLOUDFLARE_EMAIL",
    "CLOUDFLARE_GLOBAL_API_KEY",
}
REQUIRED_EXTERNAL_OPERATOR_INPUT_KEYS = {
    "CLOUDFLARE_ACCOUNT_ID",
    *LOCAL_ONLY_OPERATOR_INPUT_KEYS,
    "GITHUB_TOKEN",
    "MINIMAX_API_KEY",
    "MINIMAX_BASE_URL",
    "MINIMAX_MODEL",
    "NOTION_TOKEN",
    "NOTION_ROOT_PAGE_ID",
}
OPTIONAL_OPERATOR_INPUT_KEYS = {
    "HERMES_TELEGRAM_BOT_TOKEN",
    "HERMES_TELEGRAM_ALLOWED_USERS",
}
REQUIRED_OPERATOR_ENV_KEYS = (
    REQUIRED_OPERATOR_BOOTSTRAP_KEYS | REQUIRED_EXTERNAL_OPERATOR_INPUT_KEYS
)
OPERATOR_ENV_EXAMPLE_KEYS = REQUIRED_OPERATOR_ENV_KEYS | OPTIONAL_OPERATOR_INPUT_KEYS


def normalize_operator_ssh_cidrs(raw: str) -> str:
    """Return the canonical, fail-closed operator SSH allowlist."""
    tokens = [value for value in re.split(r"[\s,]+", raw.strip()) if value]
    if not tokens:
        raise ConfigError("MTE_OPERATOR_SSH_CIDRS must contain at least one CIDR")
    networks: set[str] = set()
    for token in tokens:
        try:
            networks.add(str(ipaddress.ip_network(token, strict=True)))
        except ValueError as exc:
            raise ConfigError(
                f"MTE_OPERATOR_SSH_CIDRS contains invalid CIDR {token!r}"
            ) from exc
    return ",".join(sorted(networks))


ONE_TIME_MIGRATION_SEEDS = {
    "MTE_PLATFORM_ROOT": "/opt/mte-platform",
    "MTE_SECRETS_ROOT": "/root/.config/mte-secrets",
    "DATA_CONTENT_PROFILE": "postgres-notion",
    "NOTION_API_BASE_URL": "https://api.notion.com/v1",
    "NOTION_API_VERSION": "2025-09-03",
    "NOTION_SYNC_BATCH_SIZE": "25",
    "NOTION_SYNC_MAX_ATTEMPTS": "8",
    "NOTION_SYNC_LEASE_SECONDS": "300",
    "NOTION_SYNC_RETRY_BASE_SECONDS": "5",
    "NOTION_SYNC_INTERVAL_SECONDS": "15",
    "PAPERCLIP_SUBDOMAIN": "paperclip",
    "KESTRA_SUBDOMAIN": "kestra",
    "MATTERMOST_SUBDOMAIN": "chat",
    "BASEROW_SUBDOMAIN": "baserow",
    "WIKIJS_SUBDOMAIN": "docs",
    "POSTGREST_SUBDOMAIN": "data-api",
    "POSTGREST_ORIGIN_PORT": "18093",
    "POSTGREST_HEALTH_URL": "http://127.0.0.1:18095/ready",
    "POSTGREST_ACCESS_CLASS": "service",
    "POSTGREST_DATA_DB_NAME": "mte_agent_data",
    "POSTGREST_DATA_DB_USER": "mte_agent_data_owner",
    "POSTGREST_READER_ROLE": "mte_pgrst_reader",
    "POSTGREST_WRITER_ROLE": "mte_pgrst_writer",
    "POSTGREST_PAPERCLIP_ROLE": "mte_pgrst_paperclip",
    "POSTGREST_ACTIVEPIECES_ROLE": "mte_pgrst_activepieces",
    "NOCODB_SUBDOMAIN": "nocodb",
    "NOCODB_ORIGIN_PORT": "18096",
    "NOCODB_HEALTH_URL": "http://127.0.0.1:18096/api/v1/health",
    "NOCODB_ACCESS_CLASS": "human",
    "NOCODB_DB_HOST": "mte-postgres",
    "NOCODB_DB_PORT": "5432",
    "NOCODB_DB_SSLMODE": "disable",
    "NOCODB_META_DB_NAME": "mte_nocodb_meta",
    "NOCODB_META_DB_USER": "mte_nocodb_meta",
    "NOCODB_DATA_DB_USER": "mte_nocodb_data",
    "NOCODB_ADMIN_EMAIL": "admin@nocodb.mte.local",
    "NOCODB_BASE_TITLE": "MTE Shared Data",
    "NOCODB_TABLE_TITLE": "prototype_items",
    "ACTIVEPIECES_SUBDOMAIN": "activepieces",
    "GRAFANA_SUBDOMAIN": "grafana",
    "SEARXNG_SUBDOMAIN": "search",
    "FIRECRAWL_SUBDOMAIN": "firecrawl",
    "TOOLHIVE_SUBDOMAIN": "toolhive",
    "NINEROUTER_SUBDOMAIN": "9router",
    "HERMES_SUBDOMAIN": "hermes",
    "DOKPLOY_SUBDOMAIN": "dokploy",
    "PAPERCLIP_PORT": "3100",
    "PAPERCLIP_LEGACY_PORT": "18110",
    "PAPERCLIP_RUNTIME_VERSION": "2026.707.0",
    "CODEX_CLI_VERSION": "0.144.4",
    "CLAUDE_CODE_CLI_VERSION": "2.1.209",
    "PI_CLI_VERSION": "0.80.7",
    "PAPERCLIP_NODE_IMAGE": "node:22-bookworm@sha256:5647be709086c696ff32edaaf1c70cd26d1da6ab2b39c32f3c7b4c4a31957e37",
    "PAPERCLIP_CPU_LIMIT": "1.0",
    "PAPERCLIP_MEMORY_LIMIT": "3g",
    "PAPERCLIP_PIDS_LIMIT": "1024",
    "KESTRA_HTTP_PORT": "18082",
    "KESTRA_HEALTH_PORT": "18081",
    "FIRECRAWL_HARNESS_STARTUP_TIMEOUT_MS": "300000",
    "DAYTONA_API_URL": "http://127.0.0.1:3310/api",
    "DAYTONA_TARGET": "us",
    "MTE_DAYTONA_ENVIRONMENT_NAME": "MTE Daytona Coding",
    "MTE_DAYTONA_CODING_IMAGE": (
        "daytonaio/sandbox:0.8.0@sha256:"
        "edb66f95f2f09a28a029a0e03d516cf5482ef13a218e93ab1d80954f6ee7ebbb"
    ),
    "MTE_DAYTONA_CODING_CPU": "1",
    "MTE_DAYTONA_CODING_MEMORY_GIB": "2",
    "MTE_DAYTONA_DISK_GIB": "20",
    "MTE_DAYTONA_TIMEOUT_MS": "300000",
    "MTE_DAYTONA_REUSE_LEASE": "true",
    "MTE_PI_CODING_AGENT_DIR": "/home/daytona/.pi/mte-profile",
    "MTE_DAYTONA_API_PORT": "3310",
    "MTE_DAYTONA_PROXY_PORT": "3410",
    "MTE_DAYTONA_DEX_PORT": "3556",
    "MTE_DAYTONA_SSH_PORT": "3222",
    "MTE_AGENT_PLANE_NETWORK": "mte-agent-plane",
    "MTE_AGENT_GATEWAY_IMAGE": "python:3.13-slim@sha256:bffeb7bd6a85767587059c6ba23e1e9122078e3aa3fa836099171b9bb5a9bb00",
    "MTE_AGENT_GATEWAY_HOST": "172.20.0.1",
    "MTE_AGENT_GATEWAY_NINEROUTER_PORT": "22080",
    "MTE_AGENT_GATEWAY_TOOLHIVE_CODEX_PORT": "22081",
    "MTE_AGENT_GATEWAY_TOOLHIVE_CLAUDE_PORT": "22082",
    "MTE_AGENT_GATEWAY_TOOLHIVE_PI_PORT": "22083",
    "MTE_AGENT_GATEWAY_NINEROUTER_BASE_URL": "http://172.20.0.1:22080",
    "MTE_AGENT_GATEWAY_NINEROUTER_OPENAI_BASE_URL": "http://172.20.0.1:22080/v1",
    "MTE_AGENT_GATEWAY_TOOLHIVE_CODEX_URL": "http://172.20.0.1:22081/mcp",
    "MTE_AGENT_GATEWAY_TOOLHIVE_CLAUDE_URL": "http://172.20.0.1:22082/mcp",
    "MTE_AGENT_GATEWAY_TOOLHIVE_PI_URL": "http://172.20.0.1:22083/mcp",
    "MTE_AGENT_GATEWAY_NINEROUTER_UPSTREAM": "http://9router:20128",
    "MTE_AGENT_GATEWAY_TOOLHIVE_CODEX_UPSTREAM": "http://toolhive:19011",
    "MTE_AGENT_GATEWAY_TOOLHIVE_CLAUDE_UPSTREAM": "http://toolhive:19012",
    "MTE_AGENT_GATEWAY_TOOLHIVE_PI_UPSTREAM": "http://toolhive:19013",
    "DOKPLOY_BASE_URL": "http://127.0.0.1:3000/api",
    "CLOUDFLARE_ENABLED": "true",
    "CLOUDFLARE_TUNNEL_NAME": "paperclip-agent-platform",
    "CLOUDFLARE_ACCESS_SESSION_DURATION": "12h",
    "CLOUDFLARE_SERVICE_TOKEN_DURATION": "8760h",
    "PAPERCLIP_ORIGIN_PORT": "3100",
    "PAPERCLIP_ACCESS_CLASS": "human",
    "KESTRA_ORIGIN_PORT": "18082",
    "KESTRA_ACCESS_CLASS": "human",
    "MATTERMOST_ORIGIN_PORT": "18065",
    "MATTERMOST_ACCESS_CLASS": "human",
    "BASEROW_ORIGIN_PORT": "18085",
    "BASEROW_ACCESS_CLASS": "human",
    "WIKIJS_ORIGIN_PORT": "18086",
    "WIKIJS_ACCESS_CLASS": "human",
    "ACTIVEPIECES_ORIGIN_PORT": "18090",
    "ACTIVEPIECES_ACCESS_CLASS": "human",
    "GRAFANA_ORIGIN_PORT": "13000",
    "GRAFANA_ACCESS_CLASS": "human",
    "SEARXNG_ORIGIN_PORT": "18088",
    "SEARXNG_ACCESS_CLASS": "human",
    "FIRECRAWL_ORIGIN_PORT": "13002",
    "FIRECRAWL_ACCESS_CLASS": "service",
    "TOOLHIVE_ORIGIN_PORT": "18880",
    "TOOLHIVE_ACCESS_CLASS": "service",
    "NINEROUTER_ORIGIN_PORT": "20128",
    "NINEROUTER_ACCESS_CLASS": "service",
    "DOKPLOY_ORIGIN_PORT": "3000",
    "DOKPLOY_ACCESS_CLASS": "human",
    "NINEROUTER_HEALTH_URL": "http://127.0.0.1:20128/api/health",
    "KESTRA_HEALTH_URL": "http://127.0.0.1:18081/health",
    "PAPERCLIP_HEALTH_URL": "http://127.0.0.1:3100/api/health",
    "TOOLHIVE_HEALTH_URL": "http://127.0.0.1:18880/api/openapi.json",
    "ACTIVEPIECES_HEALTH_URL": "http://127.0.0.1:18090/api/v1/health",
    "BASEROW_HEALTH_URL": "http://127.0.0.1:18085/api/_health/",
    "WIKIJS_HEALTH_URL": "http://127.0.0.1:18086/healthz",
    "MATTERMOST_HEALTH_URL": "http://127.0.0.1:18065/api/v4/system/ping",
    "SEARXNG_HEALTH_URL": "http://127.0.0.1:18088/",
    "FIRECRAWL_HEALTH_URL": "http://127.0.0.1:13002/",
    "OBSERVABILITY_HEALTH_URL": "http://127.0.0.1:13000/api/health",
    "PAPERCLIP_API_BASE": "http://127.0.0.1:3100",
    "PAPERCLIP_WORKSPACE_ROOT": "/workspaces/mte-isolated-canary",
    "PAPERCLIP_SECRETS_STRICT_MODE": "true",
    "BASEROW_DB_HOST": "mte-postgres",
    "BASEROW_DB_PORT": "5432",
    "BASEROW_DB_NAME": "baserow",
    "BASEROW_DB_USER": "baserow",
    "BASEROW_REDIS_HOST": "redis",
    "BASEROW_REDIS_PORT": "6379",
    "BASEROW_REDIS_DB": "0",
    "BASEROW_CPU_LIMIT": "1.0",
    "BASEROW_MEMORY_LIMIT": "2g",
    "BASEROW_ADMIN_NAME": "MTE Platform Admin",
    "BASEROW_ADMIN_EMAIL": "admin@mte.local",
    "BASEROW_WORKSPACE_NAME": "MTE Agent Workspace",
    "BASEROW_DATABASE_NAME": "MTE Agent Registry",
    "BASEROW_TABLE_NAME": "Agent Tasks",
    "BASEROW_PAPERCLIP_TOKEN_NAME": "MTE Paperclip Agent",
    "BASEROW_ACTIVEPIECES_TOKEN_NAME": "MTE Activepieces",
    "BASEROW_MCP_ENDPOINT_NAME": "MTE Agent MCP",
    "WIKIJS_DB_HOST": "mte-postgres",
    "WIKIJS_DB_PORT": "5432",
    "WIKIJS_DB_NAME": "wikijs",
    "WIKIJS_DB_USER": "wikijs",
    "WIKIJS_CPU_LIMIT": "1.0",
    "WIKIJS_MEMORY_LIMIT": "2g",
    "WIKIJS_PIDS_LIMIT": "512",
    "WIKIJS_ADMIN_EMAIL": "admin@mte.local",
    "WIKIJS_API_KEY_NAME": "MTE Agent API",
    "WIKIJS_API_KEY_EXPIRATION": "3y",
    "DAYTONA_ENABLED": "true",
    "DAYTONA_PLUGIN_VERSION": "0.1.0",
    "DAYTONA_MEMORY_GIB": "4",
    "DAYTONA_CUSTOM_IMAGE_LIFECYCLE": "true",
    "DAYTONA_PROBE_ENABLED": "true",
    "PAPERCLIP_LOOPBACK_HOST": "127.0.0.1",
    "PAPERCLIP_CONTAINER_HOST": "host.docker.internal",
    "KESTRA_LOOPBACK_HOST": "127.0.0.1",
    "E2E_CLEANUP_ENABLED": "true",
    "E2E_REQUIRE_ARTIFACTS_ENDPOINT": "true",
    "E2E_REQUIRE_GITHUB_DRAFT_PR": "true",
    "E2E_REQUIRE_CHECKS": "true",
    "TOOLHIVE_VERSION": "0.36.0",
    "TOOLHIVE_ARCHIVE_URL": "https://github.com/stacklok/toolhive/releases/download/v0.36.0/toolhive_0.36.0_linux_amd64.tar.gz",
    "TOOLHIVE_ARCHIVE_SHA256": "ca87b9d9eec394d953868a8fbbbda88d7c6105ac65c1a45327b7af75bfcfbce9",
    "TOOLHIVE_CANARY_IMAGE": "mcp/everything@sha256:330885a0c4b2eed6f0cd3aae0f0b37152ccdf2852e2f6af6d616a5d5c1e9817d",
    "TOOLHIVE_NOTION_IMAGE": "ghcr.io/stacklok/dockyard/npx/notion@sha256:180a55ce48d1d08888abb9920a6d24ba178929e4131722579466c494eec3d08f",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_CODEX_PROXY_PORT": "19011",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_CLAUDE_PROXY_PORT": "19012",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_PI_PROXY_PORT": "19013",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_CODEX_EVERYTHING_PROXY_PORT": "19211",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_CODEX_NOTION_PROXY_PORT": "19212",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_CLAUDE_EVERYTHING_PROXY_PORT": "19221",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_CLAUDE_NOTION_PROXY_PORT": "19222",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_PI_EVERYTHING_PROXY_PORT": "19231",
    "TOOLHIVE_PROFILE_CODING_DAYTONA_PI_NOTION_PROXY_PORT": "19232",
    "PROFILE_CODING_DAYTONA_CODEX_ADAPTER": "codex_local",
    "PROFILE_CODING_DAYTONA_CODEX_DEFAULT_ENVIRONMENT": "daytona-coding",
    "PROFILE_CODING_DAYTONA_CODEX_MODEL": "mte-minimax/MiniMax-M2.7-highspeed",
    "PROFILE_CODING_DAYTONA_CODEX_TIMEOUT_SEC": "1800",
    "PROFILE_CODING_DAYTONA_CODEX_MAX_CONCURRENT_RUNS": "1",
    "PROFILE_CODING_DAYTONA_CODEX_TIMEOUT_SECONDS": "1800",
    "PROFILE_CODING_DAYTONA_CODEX_CPU_LIMIT": "1",
    "PROFILE_CODING_DAYTONA_CODEX_MEMORY_LIMIT": "2Gi",
    "PROFILE_CODING_DAYTONA_CODEX_PACKAGE_CODEX_VERSION": "0.144.4",
    "PROFILE_CODING_DAYTONA_CODEX_PACKAGE_TOOLHIVE_VERSION": "0.36.0",
    "PROFILE_CODING_DAYTONA_CLAUDE_ADAPTER": "claude_local",
    "PROFILE_CODING_DAYTONA_CLAUDE_DEFAULT_ENVIRONMENT": "daytona-coding",
    "PROFILE_CODING_DAYTONA_CLAUDE_MODEL": "mte-minimax/MiniMax-M2.7-highspeed",
    "PROFILE_CODING_DAYTONA_CLAUDE_TIMEOUT_SEC": "1800",
    "PROFILE_CODING_DAYTONA_CLAUDE_MAX_CONCURRENT_RUNS": "1",
    "PROFILE_CODING_DAYTONA_CLAUDE_TIMEOUT_SECONDS": "1800",
    "PROFILE_CODING_DAYTONA_CLAUDE_CPU_LIMIT": "1",
    "PROFILE_CODING_DAYTONA_CLAUDE_MEMORY_LIMIT": "2Gi",
    "PROFILE_CODING_DAYTONA_CLAUDE_PACKAGE_CLAUDECODE_VERSION": "2.1.209",
    "PROFILE_CODING_DAYTONA_CLAUDE_PACKAGE_TOOLHIVE_VERSION": "0.36.0",
    "PROFILE_CODING_DAYTONA_PI_ADAPTER": "pi_local",
    "PROFILE_CODING_DAYTONA_PI_DEFAULT_ENVIRONMENT": "daytona-coding",
    "PROFILE_CODING_DAYTONA_PI_PROVIDER": "mte9router",
    "PROFILE_CODING_DAYTONA_PI_MODEL": "mte9router/mte-minimax/MiniMax-M2.7-highspeed",
    "PROFILE_CODING_DAYTONA_PI_TIMEOUT_SEC": "1800",
    "PROFILE_CODING_DAYTONA_PI_MAX_CONCURRENT_RUNS": "1",
    "PROFILE_CODING_DAYTONA_PI_TIMEOUT_SECONDS": "1800",
    "PROFILE_CODING_DAYTONA_PI_CPU_LIMIT": "1",
    "PROFILE_CODING_DAYTONA_PI_MEMORY_LIMIT": "2Gi",
    "PROFILE_CODING_DAYTONA_PI_PACKAGE_PI_VERSION": "0.80.7",
    "PROFILE_CODING_DAYTONA_PI_PACKAGE_TOOLHIVE_VERSION": "0.36.0",
}
PUBLIC_COMPONENT_SUBDOMAINS = {
    "paperclip": "PAPERCLIP_SUBDOMAIN",
    "kestra": "KESTRA_SUBDOMAIN",
    "mattermost": "MATTERMOST_SUBDOMAIN",
    "baserow": "BASEROW_SUBDOMAIN",
    "wikijs": "WIKIJS_SUBDOMAIN",
    "mathesar": "MATHESAR_SUBDOMAIN",
    "postgrest": "POSTGREST_SUBDOMAIN",
    "memos": "MEMOS_SUBDOMAIN",
    "activepieces": "ACTIVEPIECES_SUBDOMAIN",
    "grafana": "GRAFANA_SUBDOMAIN",
    "searxng": "SEARXNG_SUBDOMAIN",
    "firecrawl": "FIRECRAWL_SUBDOMAIN",
    "toolhive": "TOOLHIVE_SUBDOMAIN",
    "9router": "NINEROUTER_SUBDOMAIN",
    "hermes": "HERMES_SUBDOMAIN",
    "dokploy": "DOKPLOY_SUBDOMAIN",
}


class ConfigError(RuntimeError):
    pass


@contextmanager
def config_lock():
    SECRET_ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
    SECRET_ROOT.chmod(0o700)
    if os.geteuid() == 0:
        os.chown(SECRET_ROOT, 0, 0)
    with LOCK.open("a+") as handle:
        secure_path(LOCK, 0o600)
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        yield


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_path(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def missing_required(values: dict[str, str], required: set[str]) -> list[str]:
    return sorted(
        key
        for key in required
        if key not in values or (key not in OPTIONAL_EMPTY_KEYS and not values[key])
    )


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ConfigError(f"invalid canonical key {key!r}")
        if "\n" in value or "\r" in value:
            raise ConfigError(f"canonical key {key} is not single-line")
        values[key] = value
    return values


def source_state() -> tuple[dict[str, str], str]:
    if not SOURCE.is_file():
        raise ConfigError(f"canonical runtime SSOT is missing: {SOURCE}")
    stat = SOURCE.stat()
    if stat.st_uid != 0 or stat.st_mode & 0o777 != 0o600:
        raise ConfigError("canonical platform.env must be owned by root with mode 0600")
    values = parse_env(SOURCE)
    return values, sha256_path(SOURCE)


def write_env(path: Path, values: dict[str, str], *, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    secure_path(path.parent, 0o700)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text("".join(f"{key}={values[key]}\n" for key in sorted(values)))
    secure_path(temporary, mode)
    temporary.replace(path)
    secure_path(path, mode)


def config_object() -> dict[str, Any]:
    try:
        value = json.loads(CONFIG_SOURCE.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ConfigError(
            f"invalid structural config template {CONFIG_SOURCE}"
        ) from exc
    if not isinstance(value, dict):
        raise ConfigError("structural platform config must be an object")
    return value


def platform_lock_object() -> dict[str, Any]:
    try:
        value = yaml.safe_load(PLATFORM_LOCK_SOURCE.read_text())
    except (OSError, yaml.YAMLError) as exc:
        raise ConfigError(
            f"invalid structural platform lock {PLATFORM_LOCK_SOURCE}"
        ) from exc
    if not isinstance(value, dict):
        raise ConfigError("structural platform lock must be an object")
    return value


def data_content_contract():
    path = Path(__file__).with_name("data_content_plane.py")
    spec = importlib.util.spec_from_file_location("mte_data_content_plane", path)
    if spec is None or spec.loader is None:
        raise ConfigError("cannot load the reviewed data/content contract")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def active_config_object(
    cfg: dict[str, Any],
    values: dict[str, str],
    platform_lock: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if not isinstance(cfg.get("spec"), dict) or "dataContentPlane" not in cfg["spec"]:
        return cfg
    if platform_lock is None:
        platform_lock = platform_lock_object()
    contract = data_content_contract()
    try:
        return contract.filter_platform_config(cfg, platform_lock, values)
    except contract.DataContentError as exc:
        raise ConfigError(str(exc)) from exc


def compose_projection_name(compose: str | Path) -> str:
    source = Path(str(compose))
    if source.name == "compose.yaml" and source.parent.parent.name == "services":
        return f"{source.parent.name}.yaml"
    return source.name


def compose_paths(cfg: dict[str, Any]) -> list[tuple[str, Path]]:
    result = []
    for component in cfg.get("spec", {}).get("components", []):
        compose = component.get("compose")
        if compose:
            result.append(
                (
                    str(component["id"]),
                    ROOT / "templates" / "deploy" / compose_projection_name(compose),
                )
            )
    return result


def runtime_compose_path(source: Path) -> Path:
    return ROOT / "runtime" / "deploy" / source.name


def key_part(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def generated_key(component_id: str, service_name: str, suffix: str) -> str:
    return "MTE_" + "_".join(
        key_part(item) for item in (component_id, service_name, suffix) if item
    )


def scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def compose_declarations(
    component_id: str,
    path: Path,
) -> tuple[dict[str, Any], set[str], dict[str, str]]:
    try:
        document = yaml.safe_load(strip_generated_header(path.read_text()))
    except (OSError, yaml.YAMLError) as exc:
        raise ConfigError(f"invalid compose source {path}") from exc
    if not isinstance(document, dict) or not isinstance(document.get("services"), dict):
        raise ConfigError(f"compose source has no services: {path}")
    required: set[str] = set()
    seeds: dict[str, str] = {}
    raw = path.read_text()
    for match in ENV_PATTERN.finditer(raw):
        key, operator, default = match.groups()
        required.add(key)
        if operator == ":-" and default:
            seeds.setdefault(key, default)
    for service_name, service in document["services"].items():
        if not isinstance(service, dict):
            continue
        image = service.get("image")
        if isinstance(image, str) and not image.startswith("${"):
            key = generated_key(component_id, str(service_name), "IMAGE")
            required.add(key)
            seeds.setdefault(key, image)
        for field, suffix in (("cpus", "CPU_LIMIT"), ("mem_limit", "MEMORY_LIMIT")):
            value = service.get(field)
            if value is not None and not str(value).startswith("${"):
                key = generated_key(component_id, str(service_name), suffix)
                required.add(key)
                seeds.setdefault(key, scalar(value))
        for index, port in enumerate(service.get("ports", []) or [], 1):
            if not str(port).startswith("${"):
                key = generated_key(
                    component_id, str(service_name), f"PORT_{index}_MAPPING"
                )
                required.add(key)
                seeds.setdefault(key, scalar(port))
        environment = service.get("environment")
        if isinstance(environment, dict):
            for name, value in environment.items():
                if value is None or not MUTABLE_KEY_PATTERN.search(str(name)):
                    continue
                derived_ref = COMPOSE_DERIVED_ENV_REFS.get((component_id, str(name)))
                if derived_ref:
                    required.add(derived_ref)
                    continue
                text = scalar(value)
                refs = ENV_PATTERN.findall(text)
                if refs:
                    required.update(item[0] for item in refs)
                    continue
                if (
                    component_id == "firecrawl"
                    and str(name) == "HARNESS_STARTUP_TIMEOUT_MS"
                ):
                    key = "FIRECRAWL_HARNESS_STARTUP_TIMEOUT_MS"
                else:
                    key = generated_key(component_id, str(service_name), f"ENV_{name}")
                required.add(key)
                seeds.setdefault(key, text)
    return document, required, seeds


def _compose_seed_keys(cfg: dict[str, Any]) -> set[str]:
    compose_required: set[str] = set()
    for component_id, path in compose_paths(cfg):
        if not path.is_file():
            raise ConfigError(f"missing compose projection source {path}")
        _, required, _ = compose_declarations(component_id, path)
        compose_required.update(required)
    component_secrets = {
        str(key)
        for component in cfg.get("spec", {}).get("components", [])
        for key in component.get("secrets", [])
    }
    return (
        compose_required
        - component_secrets
        - DERIVED_VALUE_KEYS
        - set(ONE_TIME_MIGRATION_SEEDS)
    )


def compose_seed_catalog(cfg: dict[str, Any]) -> dict[str, str]:
    """Load the reviewed, non-secret Compose seed catalog for first install only."""
    try:
        document = json.loads(COMPOSE_SEED_SOURCE.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ConfigError(
            f"invalid Compose seed catalog {COMPOSE_SEED_SOURCE}"
        ) from exc
    if not isinstance(document, dict):
        raise ConfigError("Compose seed catalog must be an object")
    if document.get("apiVersion") != "micro-task-engine/v1alpha1":
        raise ConfigError("Compose seed catalog apiVersion is unsupported")
    if document.get("kind") != "ComposeSeedCatalog":
        raise ConfigError("Compose seed catalog kind is invalid")
    metadata = document.get("metadata")
    if not isinstance(metadata, dict) or metadata.get("contractVersion") != 1:
        raise ConfigError("Compose seed catalog contractVersion is unsupported")
    raw_seeds = document.get("seeds")
    if not isinstance(raw_seeds, dict):
        raise ConfigError("Compose seed catalog seeds must be an object")

    # The checked-in catalog covers every selectable provider, while a render
    # consumes only the selected profile's rows. This keeps one reviewed seed
    # source without leaking inactive-provider keys into canonical platform.env.
    universe_cfg = config_object()
    expected = _compose_seed_keys(universe_cfg)
    active_expected = _compose_seed_keys(cfg)
    actual = {str(key) for key in raw_seeds}
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise ConfigError(
            "Compose seed catalog coverage mismatch; "
            f"missing={','.join(missing) or '-'}; extra={','.join(extra) or '-'}"
        )

    seeds: dict[str, str] = {}
    for key in sorted(actual):
        value = raw_seeds[key]
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ConfigError(f"Compose seed catalog key {key!r} is invalid")
        if not isinstance(value, str) or not value or "\n" in value or "\r" in value:
            raise ConfigError(
                f"Compose seed catalog value for {key} must be non-empty and single-line"
            )
        if ENV_PATTERN.search(value):
            raise ConfigError(
                f"Compose seed catalog value for {key} contains an unresolved ref"
            )
        if SENSITIVE_KEY_PATTERN.search(key) and not key.endswith("_ENABLED"):
            raise ConfigError(
                f"Compose seed catalog contains sensitive-looking key {key}"
            )
        if key.endswith("_IMAGE") and not re.search(r"@sha256:[0-9a-f]{64}$", value):
            raise ConfigError(f"Compose seed catalog image {key} is not digest-pinned")
        if re.search(r"_PORT_[0-9]+_MAPPING$", key) and not value.startswith(
            "127.0.0.1:"
        ):
            raise ConfigError(f"Compose seed catalog port {key} is not loopback-only")
        seeds[key] = value
    return {key: value for key, value in seeds.items() if key in active_expected}


def compose_projection(
    component_id: str,
    path: Path,
) -> tuple[str, set[str]]:
    document, required, _ = compose_declarations(component_id, path)
    for service_name, service in document["services"].items():
        if not isinstance(service, dict):
            continue
        image = service.get("image")
        if isinstance(image, str) and not image.startswith("${"):
            service["image"] = (
                "${"
                + generated_key(component_id, str(service_name), "IMAGE")
                + ":?required}"
            )
        for field, suffix in (("cpus", "CPU_LIMIT"), ("mem_limit", "MEMORY_LIMIT")):
            value = service.get(field)
            if value is not None and not str(value).startswith("${"):
                service[field] = (
                    "${"
                    + generated_key(component_id, str(service_name), suffix)
                    + ":?required}"
                )
        ports = service.get("ports", []) or []
        service["ports"] = [
            port
            if str(port).startswith("${")
            else "${"
            + generated_key(component_id, str(service_name), f"PORT_{index}_MAPPING")
            + ":?required}"
            for index, port in enumerate(ports, 1)
        ]
        environment = service.get("environment")
        if isinstance(environment, dict):
            for name, value in list(environment.items()):
                if value is None or not MUTABLE_KEY_PATTERN.search(str(name)):
                    continue
                derived_ref = COMPOSE_DERIVED_ENV_REFS.get((component_id, str(name)))
                if derived_ref:
                    environment[name] = "${" + derived_ref + ":?required}"
                    required.add(derived_ref)
                    continue
                text = scalar(value)
                if ENV_PATTERN.search(text):
                    environment[name] = ENV_PATTERN.sub(
                        lambda match: "${" + match.group(1) + ":?required}",
                        text,
                    )
                else:
                    key = (
                        "FIRECRAWL_HARNESS_STARTUP_TIMEOUT_MS"
                        if component_id == "firecrawl"
                        and str(name) == "HARNESS_STARTUP_TIMEOUT_MS"
                        else generated_key(
                            component_id, str(service_name), f"ENV_{name}"
                        )
                    )
                    environment[name] = "${" + key + ":?required}"
    rendered = yaml.safe_dump(document, sort_keys=False, default_flow_style=False)
    rendered = ENV_PATTERN.sub(
        lambda match: "${" + match.group(1) + ":?required}",
        rendered,
    )
    return rendered, required


def profile_key(profile_ref: str, suffix: str) -> str:
    return "PROFILE_" + key_part(profile_ref) + "_" + key_part(suffix)


def profile_environment_refs(value: Any) -> set[str]:
    if isinstance(value, dict):
        return set().union(*(profile_environment_refs(item) for item in value.values()))
    if isinstance(value, list):
        return set().union(*(profile_environment_refs(item) for item in value))
    if isinstance(value, str):
        return {match.group(1) for match in ENV_PATTERN.finditer(value)}
    return set()


def profile_declarations(path: Path) -> tuple[dict[str, Any], set[str], dict[str, str]]:
    try:
        catalog = yaml.safe_load(path.read_text())
    except (OSError, yaml.YAMLError) as exc:
        raise ConfigError(f"invalid profile catalog {path}") from exc
    if not isinstance(catalog, dict):
        raise ConfigError(f"invalid profile catalog {path}")
    required: set[str] = set()
    seeds: dict[str, str] = {}
    for profile in catalog.get("profiles", []):
        ref = str(profile["ref"])
        fields: list[tuple[dict[str, Any], str, str]] = [
            (profile, "nativeAdapter", "ADAPTER"),
        ]
        if "defaultEnvironment" in profile:
            fields.append((profile, "defaultEnvironment", "DEFAULT_ENVIRONMENT"))
        adapter = profile.get("nativeAdapterConfig", {})
        fields.extend(
            [
                (adapter, "provider", "PROVIDER"),
                (adapter, "model", "MODEL"),
                (adapter, "timeoutSec", "TIMEOUT_SEC"),
            ]
        )
        limits = profile.get("limits", {})
        fields.extend(
            [
                (limits, "maxConcurrentRuns", "MAX_CONCURRENT_RUNS"),
                (limits, "timeoutSeconds", "TIMEOUT_SECONDS"),
                (limits, "cpu", "CPU_LIMIT"),
                (limits, "memory", "MEMORY_LIMIT"),
            ]
        )
        packages = profile.get("runtimePackages", {})
        for package, value in packages.items():
            fields.append((packages, str(package), f"PACKAGE_{package}_VERSION"))
        for container, name, suffix in fields:
            if name not in container:
                continue
            key = profile_key(ref, suffix)
            required.add(key)
            value = container[name]
            if not (isinstance(value, str) and ENV_PATTERN.fullmatch(value)):
                seeds.setdefault(key, scalar(value))
        # llmRouting.apiKeyRef is recorded as a declared secret dependency, but
        # declared_keys excludes it from the first render gate because 9Router
        # issues the value during the subsequent provision stage.
        llm_routing = profile.get("llmRouting", {})
        api_key_ref = (
            llm_routing.get("apiKeyRef") if isinstance(llm_routing, dict) else None
        )
        if isinstance(api_key_ref, str) and re.fullmatch(
            r"[A-Z][A-Z0-9_]*", api_key_ref
        ):
            required.add(api_key_ref)
        required.update(profile_environment_refs(profile))
    return catalog, required, seeds


def profile_projection(path: Path, values: dict[str, str]) -> tuple[str, set[str]]:
    catalog, required, _ = profile_declarations(path)
    integer_suffixes = ("_TIMEOUT_SEC", "_TIMEOUT_SECONDS", "_MAX_CONCURRENT_RUNS")

    for profile in catalog.get("profiles", []):
        ref = str(profile["ref"])
        fields: list[tuple[dict[str, Any], str, str]] = [
            (profile, "nativeAdapter", "ADAPTER")
        ]
        if "defaultEnvironment" in profile:
            fields.append((profile, "defaultEnvironment", "DEFAULT_ENVIRONMENT"))
        adapter = profile.get("nativeAdapterConfig", {})
        fields.extend(
            [
                (adapter, "provider", "PROVIDER"),
                (adapter, "model", "MODEL"),
                (adapter, "timeoutSec", "TIMEOUT_SEC"),
            ]
        )
        limits = profile.get("limits", {})
        fields.extend(
            [
                (limits, "maxConcurrentRuns", "MAX_CONCURRENT_RUNS"),
                (limits, "timeoutSeconds", "TIMEOUT_SECONDS"),
                (limits, "cpu", "CPU_LIMIT"),
                (limits, "memory", "MEMORY_LIMIT"),
            ]
        )
        packages = profile.get("runtimePackages", {})
        fields.extend(
            (packages, str(name), f"PACKAGE_{name}_VERSION") for name in packages
        )
        for container, name, suffix in fields:
            if name in container:
                container[name] = "${" + profile_key(ref, suffix) + ":?required}"

    def resolve(value: Any) -> Any:
        if isinstance(value, dict):
            return {key: resolve(nested) for key, nested in value.items()}
        if isinstance(value, list):
            return [resolve(nested) for nested in value]
        if isinstance(value, str):
            match = ENV_PATTERN.fullmatch(value)
            if match:
                key = match.group(1)
                if key == "WORKSPACE":
                    return value
                if key not in values:
                    raise ConfigError(
                        f"canonical platform.env is missing required key {key}"
                    )
                raw = values[key]
                if key.endswith(integer_suffixes):
                    return int(raw)
                return raw
            matches = list(ENV_PATTERN.finditer(value))
            if matches:
                for nested_match in matches:
                    key = nested_match.group(1)
                    if SENSITIVE_KEY_PATTERN.search(key) and not key.endswith(
                        "_ENABLED"
                    ):
                        raise ConfigError(
                            f"profile strings cannot interpolate sensitive key {key}"
                        )
                    if key not in values:
                        raise ConfigError(
                            f"canonical platform.env is missing required key {key}"
                        )
                return ENV_PATTERN.sub(
                    lambda nested_match: values[nested_match.group(1)], value
                )
        return value

    rendered = resolve(catalog)
    rendered["_generated"] = {
        "doNotEdit": True,
        "generatorVersion": GENERATOR_VERSION,
    }
    return yaml.safe_dump(rendered, sort_keys=False, default_flow_style=False), required


def declared_keys(
    cfg: dict[str, Any],
    values: dict[str, str] | None = None,
) -> tuple[set[str], dict[str, set[str]], dict[str, str]]:
    required: set[str] = set()
    service_keys: dict[str, set[str]] = {}
    seeds: dict[str, str] = {}
    active_component_ids = {
        str(component.get("id"))
        for component in cfg.get("spec", {}).get("components", [])
        if isinstance(component, dict) and component.get("id")
    }
    for component_id, path in compose_paths(cfg):
        if not path.is_file():
            raise ConfigError(f"missing compose projection source {path}")
        keys = service_keys.setdefault(component_id, set())
        _, compose_keys, _ = compose_declarations(component_id, path)
        required.update(compose_keys)
        keys.update(compose_keys)
    for component in cfg.get("spec", {}).get("components", []):
        keys = service_keys.setdefault(str(component["id"]), set())
        for key in component.get("secrets", []):
            required.add(str(key))
            keys.add(str(key))
    required.update(
        {
            "FIRECRAWL_HARNESS_STARTUP_TIMEOUT_MS",
            "FIRECRAWL_API_MEMORY_LIMIT",
        }
    )
    service_keys.setdefault("firecrawl", set()).update(
        {
            "FIRECRAWL_HARNESS_STARTUP_TIMEOUT_MS",
            "FIRECRAWL_API_MEMORY_LIMIT",
        }
    )
    if "baserow" in active_component_ids:
        service_keys.setdefault("baserow", set()).update(
            {
                "BASEROW_PUBLIC_URL",
                "BASEROW_PAPERCLIP_TOKEN",
                "BASEROW_PAPERCLIP_TOKEN_ID",
                "BASEROW_ACTIVEPIECES_TOKEN",
                "BASEROW_ACTIVEPIECES_TOKEN_ID",
                "BASEROW_MCP_ENDPOINT_KEY",
                "BASEROW_MCP_ENDPOINT_ID",
                "BASEROW_WORKSPACE_ID",
                "BASEROW_DATABASE_ID",
                "BASEROW_TABLE_ID",
            }
        )
    if "wikijs" in active_component_ids:
        service_keys.setdefault("wikijs", set()).update(
            {"WIKIJS_SITE_URL", "WIKIJS_API_TOKEN", "WIKIJS_API_TOKEN_ID"}
        )
    if "postgrest" in active_component_ids:
        service_keys.setdefault("postgrest", set()).update(
            {
                "POSTGREST_PUBLIC_URL",
                "POSTGREST_PAPERCLIP_TOKEN",
                "POSTGREST_ACTIVEPIECES_TOKEN",
            }
        )
    if "nocodb" in active_component_ids:
        service_keys.setdefault("nocodb", set()).update(
            {
                "NOCODB_PUBLIC_URL",
                "NOCODB_API_TOKEN",
                "NOCODB_API_TOKEN_ID",
                "NOCODB_API_TOKEN_SHA256",
                "NOCODB_BASE_ID",
                "NOCODB_SOURCE_ID",
                "NOCODB_TABLE_ID",
            }
        )
    selected_profile = str(
        (values or ONE_TIME_MIGRATION_SEEDS).get(
            "DATA_CONTENT_PROFILE", ONE_TIME_MIGRATION_SEEDS["DATA_CONTENT_PROFILE"]
        )
    ).strip()
    if selected_profile == "postgres-notion":
        notion_keys = {
            "NOTION_TOKEN",
            "NOTION_API_BASE_URL",
            "NOTION_API_VERSION",
            "NOTION_ROOT_PAGE_ID",
            "NOTION_DOCUMENTS_PAGE_ID",
            "NOTION_TABLE_DATABASE_ID",
            "NOTION_TABLE_DATA_SOURCE_ID",
            "NOTION_WORKSPACE_ID",
            "NOTION_BOT_ID",
        }
        required.update(notion_keys)
        service_keys.setdefault("notion", set()).update(notion_keys)

    def refs(value: Any) -> None:
        if isinstance(value, dict):
            for key, nested in value.items():
                if (
                    key.endswith("Ref")
                    and isinstance(nested, str)
                    and re.fullmatch(r"[A-Z][A-Z0-9_]*", nested)
                ):
                    required.add(nested)
                elif key.endswith("Refs") and isinstance(nested, list):
                    required.update(
                        str(item)
                        for item in nested
                        if re.fullmatch(r"[A-Z][A-Z0-9_]*", str(item))
                    )
                refs(nested)
        elif isinstance(value, list):
            for nested in value:
                refs(nested)
        elif isinstance(value, str):
            required.update(match.group(1) for match in ENV_PATTERN.finditer(value))

    refs(cfg)
    required.difference_update(DERIVED_VALUE_KEYS)
    if PROFILE_SOURCE.is_file():
        _, profile_keys, _ = profile_declarations(PROFILE_SOURCE)
        required.update(profile_keys)
    required.difference_update(POST_RENDER_PROVISIONED_KEYS)
    required.update(ONE_TIME_MIGRATION_SEEDS)
    for key, value in ONE_TIME_MIGRATION_SEEDS.items():
        seeds.setdefault(key, value)
    required.update(OPTIONAL_EMPTY_KEYS)
    for key in OPTIONAL_EMPTY_KEYS:
        seeds.setdefault(key, "")
    required.difference_update(PUBLIC_URL_PROJECTIONS)
    required.add("PAPERCLIP_PORT")
    spec = cfg.get("spec", {})
    host = spec.get("host", {}) if isinstance(spec, dict) else {}
    if isinstance(host, dict) and host.get("ssh"):
        seeds.setdefault("MTE_SSH_TARGET", str(host["ssh"]))
    domain = (
        spec.get("resolvedDomain") or spec.get("domain")
        if isinstance(spec, dict)
        else ""
    )
    if domain:
        seeds.setdefault("PLATFORM_BASE_DOMAIN", str(domain))
    for component in spec.get("components", []) if isinstance(spec, dict) else []:
        if component.get("id") != "paperclip":
            continue
        url = str(component.get("health", {}).get("url", ""))
        match = re.search(r":([0-9]+)/", url)
        if match:
            seeds.setdefault("PAPERCLIP_PORT", match.group(1))
    return required, service_keys, seeds


def init_source(imported: dict[str, str]) -> dict[str, Any]:
    if SOURCE.exists():
        stat = SOURCE.stat()
        if stat.st_uid != 0 or stat.st_mode & 0o777 != 0o600:
            raise ConfigError(
                "refusing to initialize an incorrectly permissioned canonical env"
            )
    values = parse_env(SOURCE)
    fresh_source = not values
    migrated_keys: set[str] = set()
    for legacy_key, (
        expected_value,
        canonical_key,
        canonical_value,
    ) in REVIEWED_CANONICAL_KEY_MIGRATIONS.items():
        if values.get(legacy_key) == expected_value:
            values.pop(legacy_key)
            if not values.get(canonical_key):
                values[canonical_key] = canonical_value
                migrated_keys.add(canonical_key)
    for key, (old_value, new_value) in REVIEWED_CANONICAL_VALUE_MIGRATIONS.items():
        if values.get(key) == old_value:
            values[key] = new_value
            migrated_keys.add(key)
    imported = dict(imported)
    selected_notion_token = next(
        (
            str(imported[key]).strip()
            for key in NOTION_TOKEN_IMPORT_PRIORITY
            if str(imported.get(key, "")).strip()
        ),
        "",
    )
    for key in NOTION_TOKEN_IMPORT_PRIORITY:
        imported.pop(key, None)
    if selected_notion_token and not values.get("NOTION_TOKEN", "").strip():
        imported["NOTION_TOKEN"] = selected_notion_token
    selection_values = dict(ONE_TIME_MIGRATION_SEEDS)
    selection_values.update(imported)
    selection_values.update(values)
    if not selection_values.get("DATA_CONTENT_PROFILE", "").strip():
        selection_values["DATA_CONTENT_PROFILE"] = ONE_TIME_MIGRATION_SEEDS[
            "DATA_CONTENT_PROFILE"
        ]
    cfg = active_config_object(
        config_object(),
        selection_values,
    )
    required, _, seeds = declared_keys(cfg, selection_values)
    missing_operator_inputs = sorted(
        key
        for key in REQUIRED_OPERATOR_BOOTSTRAP_KEYS & required
        if not str(values.get(key) or imported.get(key) or "").strip()
    )
    if missing_operator_inputs:
        raise ConfigError(
            "explicit operator bootstrap input is missing required keys: "
            + ", ".join(missing_operator_inputs)
        )
    if "MTE_OPERATOR_SSH_CIDRS" in required:
        raw_operator_cidrs = str(
            values.get("MTE_OPERATOR_SSH_CIDRS")
            or imported.get("MTE_OPERATOR_SSH_CIDRS")
            or ""
        ).strip()
        canonical_operator_cidrs = normalize_operator_ssh_cidrs(raw_operator_cidrs)
        if raw_operator_cidrs != canonical_operator_cidrs:
            raise ConfigError(
                "MTE_OPERATOR_SSH_CIDRS must be sorted, unique, normalized and "
                f"comma-separated: {canonical_operator_cidrs}"
            )
    aliases = {
        "MTE_DOMAIN": "PLATFORM_BASE_DOMAIN",
        "PLATFORM_DOMAIN": "PLATFORM_BASE_DOMAIN",
        "CLOUDFLARE_BASE_DOMAIN": "PLATFORM_BASE_DOMAIN",
        "GH_TOKEN": "GITHUB_TOKEN",
        "MINIMAX_OPENAI_ENDPOINT": "MINIMAX_BASE_URL",
        "PRIN7R_NOTION_TOKEN": "NOTION_TOKEN",
        "PRIN7R_NOTION_API_KEY": "NOTION_TOKEN",
        # Atomic in-memory key moves for the last commercial-component
        # migration. The legacy keys are removed before platform.env is
        # written, so the credential value is never persisted twice.
        "NOCODB_DB_USER": "POSTGRES_ADMIN_USER",
        "NOCODB_DB_PASSWORD": "POSTGRES_ADMIN_PASSWORD",
        "NOCODB_DB_NAME": "POSTGRES_ADMIN_DB",
    }
    clean_install_aliases = {"PRIN7R_NOTION_PAGE_ID": "NOTION_ROOT_PAGE_ID"}
    allowed_imports = required | set(aliases)
    if selection_values["DATA_CONTENT_PROFILE"] == "postgres-notion":
        # Reuse operator-reviewed Notion resources on an existing deployment.
        # These non-secret IDs remain fill-only; the provisioner creates only
        # resources whose canonical ID is absent.
        allowed_imports.update(NOTION_BOOTSTRAP_ID_KEYS)
    if fresh_source:
        allowed_imports.update(clean_install_aliases)
    created = []
    # Legacy migration is fill-only.  A repeated init must never overwrite a
    # value already issued or rotated on the server (for example Cloudflare or
    # 9Router credentials).
    for key, value in imported.items():
        if value and key in allowed_imports and not values.get(key):
            values[key] = value
    if fresh_source:
        for legacy, canonical in clean_install_aliases.items():
            if not values.get(canonical) and values.get(legacy):
                values[canonical] = values[legacy]
                created.append(canonical)
            values.pop(legacy, None)
    for legacy, canonical in aliases.items():
        if not values.get(canonical) and values.get(legacy):
            values[canonical] = values[legacy]
            created.append(canonical)
        values.pop(legacy, None)
    for key, (old_value, new_value) in REVIEWED_CANONICAL_VALUE_MIGRATIONS.items():
        if values.get(key) == old_value:
            values[key] = new_value
            migrated_keys.add(key)
    for derived in DERIVED_VALUE_KEYS:
        values.pop(derived, None)
    # The reviewed Compose catalog is bootstrap-only except for explicitly
    # reviewed fill-only migrations.  Existing non-empty canonical values win,
    # so an operator override and every secret remain untouched.
    reviewed_compose_missing = {
        key
        for key in required
        & (
            REVIEWED_COMPOSE_SEED_MIGRATIONS
            | REVIEWED_TOOLHIVE_COMPOSE_SEED_MIGRATIONS
            | REVIEWED_ACTIVEPIECES_COMPOSE_SEED_MIGRATIONS
        )
        if not values.get(key, "").strip()
    }
    if fresh_source or reviewed_compose_missing:
        compose_seeds = compose_seed_catalog(cfg)
        overlap = sorted(set(seeds) & set(compose_seeds))
        if overlap:
            raise ConfigError(
                "Compose and general bootstrap seed classes overlap: "
                + ", ".join(overlap)
            )
        if fresh_source:
            for key, value in compose_seeds.items():
                seeds.setdefault(key, value)
        else:
            unavailable = sorted(reviewed_compose_missing - set(compose_seeds))
            if unavailable:
                raise ConfigError(
                    "reviewed Compose migration seed is unavailable: "
                    + ", ".join(unavailable)
                )
            for key in reviewed_compose_missing:
                values[key] = compose_seeds[key]
                created.append(key)
    for key, value in seeds.items():
        if key in DERIVED_VALUE_KEYS:
            continue
        if key not in values or (
            key == "DATA_CONTENT_PROFILE" and not values[key].strip()
        ):
            values[key] = value
            created.append(key)
    missing = missing_required(values, required)
    # Init may run before generated service credentials exist.  It reports
    # missing refs but never fabricates external credentials.
    write_env(SOURCE, values, mode=0o600)
    return {
        "initialized": True,
        "createdKeys": sorted(created),
        "migratedKeys": sorted(migrated_keys),
        "missingKeys": missing,
    }


def merge_notion_provision(
    payload: dict[str, Any], *, expect_idempotent: bool = False
) -> dict[str, Any]:
    """Fill canonical Notion resource IDs from the governed provisioner output.

    The caller passes the producer JSON over stdin.  Only the five reviewed,
    non-secret Notion identity keys may cross this boundary.  Existing values
    must either match exactly or the whole update is rejected before writing.
    """

    if (
        payload.get("apiVersion") != "micro-task-engine/v1alpha1"
        or payload.get("kind") != "NotionConnectorProvision"
        or payload.get("status") != "converged"
        or payload.get("ok") is not True
        or payload.get("redacted") is not True
        or payload.get("dataContentProfile") != "postgres-notion"
    ):
        raise ConfigError("notion provision envelope is invalid")
    updates = payload.get("environmentUpdates")
    changed_keys = payload.get("changedKeys")
    if not isinstance(updates, dict) or not updates:
        raise ConfigError("notion provision updates are missing")
    if set(updates) - NOTION_BOOTSTRAP_ID_KEYS:
        raise ConfigError("notion provision contains an unreviewed update key")
    if (
        not isinstance(changed_keys, list)
        or any(not isinstance(key, str) for key in changed_keys)
        or len(changed_keys) != len(set(changed_keys))
        or set(changed_keys) - NOTION_BOOTSTRAP_ID_KEYS
    ):
        raise ConfigError("notion provision changedKeys are invalid")

    validated: dict[str, str] = {}
    for key, raw_value in updates.items():
        if not isinstance(raw_value, str) or raw_value != raw_value.strip():
            raise ConfigError(f"notion provision UUID is invalid for {key}")
        try:
            canonical = str(uuid.UUID(raw_value))
        except (ValueError, AttributeError) as exc:
            raise ConfigError(f"notion provision UUID is invalid for {key}") from exc
        if canonical != raw_value:
            raise ConfigError(f"notion provision UUID is not canonical for {key}")
        validated[key] = canonical

    values, _ = source_state()
    if values.get("DATA_CONTENT_PROFILE", "").strip() != "postgres-notion":
        raise ConfigError("notion provision profile does not match canonical source")
    missing = {key for key in validated if not values.get(key, "").strip()}
    if set(changed_keys) != missing:
        raise ConfigError("notion provision changedKeys do not match canonical source")
    for key, value in validated.items():
        existing = values.get(key, "").strip()
        if existing and existing != value:
            raise ConfigError(f"refusing to overwrite canonical Notion ID {key}")
    if expect_idempotent and missing:
        raise ConfigError("notion provision did not converge idempotently")

    for key in missing:
        values[key] = validated[key]
    if missing:
        write_env(SOURCE, values, mode=0o600)
    return {
        "acceptedKeys": sorted(validated),
        "mergedKeys": sorted(missing),
        "unchangedKeys": sorted(set(validated) - missing),
        "idempotent": not missing,
        "sourceSha256": sha256_path(SOURCE),
    }


def generated_header(source_sha: str) -> str:
    return (
        f"{GENERATED_PREFIX}sourceSha256={source_sha}; "
        f"generatorVersion={GENERATOR_VERSION}\n"
    )


def strip_generated_header(text: str) -> str:
    lines = text.splitlines(keepends=True)
    if lines and lines[0].startswith(GENERATED_PREFIX):
        return "".join(lines[1:])
    return text


def projection_row(path: Path, source_sha: str) -> dict[str, str]:
    return {
        "path": str(path),
        "contentSha256": sha256_path(path),
        "sourceSha256": source_sha,
        "generatorVersion": GENERATOR_VERSION,
    }


def atomic_text(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path == SECRET_ROOT or SECRET_ROOT in path.parents:
        secure_path(path.parent, 0o700)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content)
    secure_path(temporary, mode)
    temporary.replace(path)
    secure_path(path, mode)


def secure_path(path: Path, mode: int) -> None:
    """Apply the root-only ownership contract without weakening local tests."""
    path.chmod(mode)
    if os.geteuid() == 0:
        os.chown(path, 0, 0)


def harden_secret_projections(manifest: dict[str, Any]) -> None:
    """Re-assert ownership/modes for canonical and generated secret artifacts."""
    secure_path(SECRET_ROOT, 0o700)
    files = {SOURCE, MANIFEST}
    files.update(
        path
        for name in (".platform-env.lock", ".platform.env.lock", "platform.env.lock")
        if (path := SECRET_ROOT / name).exists()
    )
    for row in manifest.get("projections", []):
        if not isinstance(row, dict) or not row.get("path"):
            continue
        path = Path(str(row["path"]))
        if path == SECRET_ROOT or SECRET_ROOT in path.parents:
            files.add(path)
    for path in sorted(files, key=str):
        if not path.is_file():
            raise ConfigError(f"secret projection is missing: {path}")
        secure_path(path, 0o600)
        parent = path.parent
        while parent == SECRET_ROOT or SECRET_ROOT in parent.parents:
            secure_path(parent, 0o700)
            if parent == SECRET_ROOT:
                break
            parent = parent.parent


def cloudflare_apps_projection(
    cfg: dict[str, Any],
    values: dict[str, str],
    base_domain: str,
    source_sha: str,
    data_content_plane: dict[str, Any],
    data_content_plane_sha: str,
) -> dict[str, Any]:
    cloudflare = cfg.get("spec", {}).get("cloudflare", {})
    contract = data_content_contract()
    try:
        try:
            lock = platform_lock_object()
        except ConfigError:
            installed = Path(__file__).resolve()
            source_root = (
                installed.parents[2]
                if installed.parent.name == "platform-cli"
                and installed.parent.parent.name == "tools"
                else installed.parents[1]
            )
            local_lock = source_root / "config" / "platform.lock.yaml"
            lock = yaml.safe_load(local_lock.read_text())
        registry = contract.validate_registry(lock)
    except (OSError, yaml.YAMLError, contract.DataContentError) as exc:
        raise ConfigError(str(exc)) from exc
    provider_components = (
        {
            str(component_id)
            for bundle in registry.values()
            for component_id in bundle["componentIds"]
        }
        if isinstance(registry, dict)
        else set()
    )
    selected_components = {
        str(component_id) for component_id in data_content_plane.get("componentIds", [])
    }
    declarations: list[dict[str, Any]] = []
    for component in cfg.get("spec", {}).get("components", []):
        component_id = (
            str(component.get("id", "")) if isinstance(component, dict) else ""
        )
        if (
            component_id in provider_components
            and component_id not in selected_components
        ):
            continue
        if isinstance(component, dict) and isinstance(component.get("exposure"), dict):
            declarations.append({"id": component.get("id"), **component["exposure"]})
    additional = (
        cloudflare.get("additionalApps", []) if isinstance(cloudflare, dict) else []
    )
    if not isinstance(additional, list):
        raise ConfigError("cloudflare.additionalApps must be a list")
    declarations.extend(row for row in additional if isinstance(row, dict))

    apps: dict[str, dict[str, str]] = {}
    hostnames: set[str] = set()
    for declaration in declarations:
        app_id = str(declaration.get("id", "")).strip()
        if not app_id or app_id in apps:
            raise ConfigError("Cloudflare applications require unique non-empty ids")
        refs = {
            name: str(declaration.get(name, "")).strip()
            for name in ("subdomainRef", "originPortRef", "accessClassRef")
        }
        if any(not re.fullmatch(r"[A-Z][A-Z0-9_]*", ref) for ref in refs.values()):
            raise ConfigError(
                f"Cloudflare application {app_id} has an invalid canonical ref"
            )
        label = values.get(refs["subdomainRef"], "").strip().lower()
        port = values.get(refs["originPortRef"], "").strip()
        access_class = values.get(refs["accessClassRef"], "").strip().lower()
        if not re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", label):
            raise ConfigError(
                f"Cloudflare application {app_id} has an invalid subdomain label"
            )
        if not port.isdigit() or not 1 <= int(port) <= 65535:
            raise ConfigError(
                f"Cloudflare application {app_id} has an invalid origin port"
            )
        if access_class not in {"human", "service"}:
            raise ConfigError(
                f"Cloudflare application {app_id} has an invalid access class"
            )
        hostname = f"{label}.{base_domain}"
        if hostname in hostnames:
            raise ConfigError(
                f"Cloudflare application {app_id} has a duplicate hostname"
            )
        apps[app_id] = {
            "hostname": hostname,
            "origin": f"http://127.0.0.1:{int(port)}",
            "accessClass": access_class,
        }
        hostnames.add(hostname)
    if not apps:
        raise ConfigError("Cloudflare application registry is empty")
    roles = data_content_plane.get("roles", {})
    providers = data_content_plane.get("providers", {})
    logical_roles: dict[str, dict[str, str]] = {}
    for role_id in ("tablesUi", "documentsUi"):
        role = roles.get(role_id) if isinstance(roles, dict) else None
        provider_id = str(role.get("providerId", "")) if isinstance(role, dict) else ""
        provider = (
            providers.get(provider_id)
            if isinstance(providers, dict) and provider_id
            else None
        )
        if isinstance(provider, dict) and provider.get("deployment") == "external":
            continue
        component_id = ""
        if isinstance(role, dict):
            component_id = str(role.get("componentId", ""))
        if not component_id and isinstance(provider, dict):
            component_id = str(provider.get("componentId") or "")
        if component_id not in apps:
            raise ConfigError(
                f"logical data/content role {role_id} is not Cloudflare-exposed"
            )
        logical_roles[role_id] = {
            "applicationId": component_id,
            "hostname": apps[component_id]["hostname"],
            "accessClass": apps[component_id]["accessClass"],
        }
    return {
        "_generated": {
            "doNotEdit": True,
            "sourceSha256": source_sha,
            "generatorVersion": GENERATOR_VERSION,
        },
        "baseDomain": base_domain,
        "apps": dict(sorted(apps.items())),
        "dataContent": {
            "profile": data_content_plane.get("profile"),
            "projectionSha256": data_content_plane_sha,
            "roles": logical_roles,
        },
    }


def apply_public_projections(
    cfg: dict[str, Any], values: dict[str, str], base_domain: str
) -> None:
    active_subdomain_refs = {
        str(exposure.get("subdomainRef"))
        for component in cfg.get("spec", {}).get("components", [])
        if isinstance(component, dict)
        and isinstance((exposure := component.get("exposure")), dict)
        and exposure.get("subdomainRef")
    }
    for key, subdomain_ref in PUBLIC_URL_PROJECTIONS.items():
        if subdomain_ref not in active_subdomain_refs:
            continue
        subdomain = values.get(subdomain_ref, "").strip().strip(".")
        if not subdomain:
            raise ConfigError(f"canonical platform.env is missing {subdomain_ref}")
        suffix = "/" if key == "SEARXNG_BASE_URL" else ""
        values[key] = f"https://{subdomain}.{base_domain}{suffix}"
    if "MATHESAR_SUBDOMAIN" in active_subdomain_refs:
        hostname = values["MATHESAR_PUBLIC_URL"].removeprefix("https://")
        values["MATHESAR_DOMAIN_NAME"] = hostname
        values["MATHESAR_ALLOWED_HOSTS"] = hostname
    if "MEMOS_SUBDOMAIN" in active_subdomain_refs:
        values["MEMOS_MCP_URL"] = values["MEMOS_PUBLIC_URL"].rstrip("/") + "/mcp"


def render() -> dict[str, Any]:
    values, source_sha = source_state()
    values = dict(values)
    base_domain = values.get("PLATFORM_BASE_DOMAIN", "").strip().strip(".")
    if not base_domain:
        raise ConfigError("canonical platform.env is missing PLATFORM_BASE_DOMAIN")
    platform_lock = platform_lock_object()
    cfg = active_config_object(config_object(), values, platform_lock)
    apply_public_projections(cfg, values, base_domain)
    values["AP_REDIS_URL"] = (
        "redis://:" + values["AP_REDIS_PASSWORD"] + "@mte-activepieces-redis:6379/0"
    )
    if values.get("BASEROW_DB_PASSWORD"):
        values["BASEROW_DATABASE_URL"] = (
            "postgresql://"
            + quote(values["BASEROW_DB_USER"], safe="")
            + ":"
            + quote(values["BASEROW_DB_PASSWORD"], safe="")
            + "@"
            + values["BASEROW_DB_HOST"]
            + ":"
            + values["BASEROW_DB_PORT"]
            + "/"
            + quote(values["BASEROW_DB_NAME"], safe="")
        )
    if values.get("BASEROW_REDIS_PASSWORD"):
        values["BASEROW_REDIS_URL"] = (
            "redis://:"
            + quote(values["BASEROW_REDIS_PASSWORD"], safe="")
            + "@"
            + values["BASEROW_REDIS_HOST"]
            + ":"
            + values["BASEROW_REDIS_PORT"]
            + "/"
            + values["BASEROW_REDIS_DB"]
        )
    if values.get("MEMOS_DB_PASSWORD"):
        values["MEMOS_DSN"] = (
            "postgresql://"
            + quote(values["MEMOS_DB_USER"], safe="")
            + ":"
            + quote(values["MEMOS_DB_PASSWORD"], safe="")
            + "@"
            + values["MEMOS_DB_HOST"]
            + ":"
            + values["MEMOS_DB_PORT"]
            + "/"
            + quote(values["MEMOS_DB_NAME"], safe="")
            + "?sslmode="
            + quote(values["MEMOS_DB_SSLMODE"], safe="")
        )
    if values.get("NOCODB_META_DB_PASSWORD"):
        values["NOCODB_META_DSN"] = (
            "pg://"
            + values["NOCODB_DB_HOST"]
            + ":"
            + values["NOCODB_DB_PORT"]
            + "?u="
            + quote(values["NOCODB_META_DB_USER"], safe="")
            + "&p="
            + quote(values["NOCODB_META_DB_PASSWORD"], safe="")
            + "&d="
            + quote(values["NOCODB_META_DB_NAME"], safe="")
        )
    if values.get("FIRECRAWL_REDIS_PASSWORD"):
        values["FIRECRAWL_REDIS_URL"] = (
            "redis://:" + values["FIRECRAWL_REDIS_PASSWORD"] + "@redis:6379"
        )
    if values.get("SEARXNG_VALKEY_PASSWORD"):
        values["SEARXNG_VALKEY_URL"] = (
            "redis://:" + values["SEARXNG_VALKEY_PASSWORD"] + "@valkey:6379/0"
        )
    required, service_keys, _ = declared_keys(cfg, values)
    missing = missing_required(values, required)
    if missing:
        raise ConfigError(
            "canonical platform.env is missing required keys: " + ", ".join(missing)
        )

    projections: list[dict[str, str]] = []
    contract = data_content_contract()
    try:
        data_content_plane = contract.resolve_from_paths(
            cfg,
            platform_lock,
            values,
            config_path=CONFIG_SOURCE,
            lock_path=PLATFORM_LOCK_SOURCE,
            source_sha256=source_sha,
            generator_version=GENERATOR_VERSION,
        )
    except contract.DataContentError as exc:
        raise ConfigError(str(exc)) from exc
    atomic_text(
        DATA_CONTENT_PLANE,
        json.dumps(data_content_plane, indent=2, sort_keys=True) + "\n",
        0o600,
    )
    projections.append(projection_row(DATA_CONTENT_PLANE, source_sha))
    data_content_plane_sha = sha256_path(DATA_CONTENT_PLANE)

    cloudflare_apps = cloudflare_apps_projection(
        cfg,
        values,
        base_domain,
        source_sha,
        data_content_plane,
        data_content_plane_sha,
    )
    atomic_text(
        CLOUDFLARE_APPS,
        json.dumps(cloudflare_apps, indent=2, sort_keys=True) + "\n",
        0o600,
    )
    projections.append(projection_row(CLOUDFLARE_APPS, source_sha))

    api_token = values.get("CLOUDFLARE_API_TOKEN", "").strip()
    if not api_token:
        raise ConfigError("canonical platform.env is missing CLOUDFLARE_API_TOKEN")
    atomic_text(
        CLOUDFLARE_API_ENV,
        generated_header(source_sha) + f"CLOUDFLARE_API_TOKEN={api_token}\n",
        0o600,
    )
    projections.append(projection_row(CLOUDFLARE_API_ENV, source_sha))

    runtime_credential_keys = (
        "CLOUDFLARE_TUNNEL_TOKEN",
        "CLOUDFLARE_ACCESS_SERVICE_TOKEN_ID",
        "CLOUDFLARE_ACCESS_CLIENT_ID",
        "CLOUDFLARE_ACCESS_CLIENT_SECRET",
        "CLOUDFLARE_ACCESS_EXPIRES_AT",
    )
    runtime_present = [
        bool(values.get(key, "").strip()) for key in runtime_credential_keys
    ]
    if any(runtime_present) and not all(runtime_present):
        raise ConfigError("canonical Cloudflare runtime credentials are incomplete")
    if all(runtime_present):
        atomic_text(
            CLOUDFLARE_TUNNEL_TOKEN,
            values["CLOUDFLARE_TUNNEL_TOKEN"].strip() + "\n",
            0o600,
        )
        projections.append(projection_row(CLOUDFLARE_TUNNEL_TOKEN, source_sha))
        access_payload = {
            "id": values["CLOUDFLARE_ACCESS_SERVICE_TOKEN_ID"].strip(),
            "client_id": values["CLOUDFLARE_ACCESS_CLIENT_ID"].strip(),
            "client_secret": values["CLOUDFLARE_ACCESS_CLIENT_SECRET"].strip(),
            "expires_at": values["CLOUDFLARE_ACCESS_EXPIRES_AT"].strip(),
            "_generated": {
                "doNotEdit": True,
                "sourceSha256": source_sha,
                "generatorVersion": GENERATOR_VERSION,
            },
        }
        atomic_text(
            CLOUDFLARE_ACCESS_TOKEN,
            json.dumps(access_payload, indent=2, sort_keys=True) + "\n",
            0o600,
        )
        projections.append(projection_row(CLOUDFLARE_ACCESS_TOKEN, source_sha))
    SERVICE_ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
    for component_id, keys in sorted(service_keys.items()):
        selected = {key: values[key] for key in sorted(keys) if key in values}
        path = SERVICE_ROOT / f"{component_id}.env"
        content = generated_header(source_sha) + "".join(
            f"{key}={selected[key]}\n" for key in sorted(selected)
        )
        atomic_text(path, content, 0o600)
        projections.append(projection_row(path, source_sha))

    for component_id, source_path in compose_paths(cfg):
        content, _ = compose_projection(component_id, source_path)
        runtime_path = runtime_compose_path(source_path)
        atomic_text(runtime_path, generated_header(source_sha) + content, 0o600)
        projections.append(projection_row(runtime_path, source_sha))

    if PROFILE_SOURCE.is_file():
        content, _ = profile_projection(PROFILE_SOURCE, values)
        profile_value = yaml.safe_load(content)
        if not isinstance(profile_value, dict):
            raise ConfigError("rendered profile catalog is not an object")
        profile_value["_generated"]["sourceSha256"] = source_sha
        atomic_text(
            PROFILE_RUNTIME,
            yaml.safe_dump(
                profile_value, sort_keys=False, default_flow_style=False
            ),
            0o600,
        )
        projections.append(projection_row(PROFILE_RUNTIME, source_sha))

    active_component_ids = {
        str(component.get("id"))
        for component in cfg.get("spec", {}).get("components", [])
        if isinstance(component, dict) and component.get("id")
    }
    public_urls = {
        component: f"https://{values[subdomain_ref]}.{base_domain}"
        for component, subdomain_ref in PUBLIC_COMPONENT_SUBDOMAINS.items()
        if component in active_component_ids
    }
    public_payload = {
        "_generated": {
            "doNotEdit": True,
            "sourceSha256": source_sha,
            "generatorVersion": GENERATOR_VERSION,
        },
        "baseDomainRef": "PLATFORM_BASE_DOMAIN",
        "urls": public_urls,
        "dataContentRoles": {
            role_id: values[str(role["endpointRef"])]
            for role_id, role in data_content_plane["roles"].items()
        },
        "origins": {},
    }
    atomic_text(
        PUBLIC_URLS, json.dumps(public_payload, indent=2, sort_keys=True) + "\n", 0o600
    )
    projections.append(projection_row(PUBLIC_URLS, source_sha))

    def resolve_config(value: Any) -> Any:
        if isinstance(value, dict):
            return {key: resolve_config(nested) for key, nested in value.items()}
        if isinstance(value, list):
            return [resolve_config(nested) for nested in value]
        if isinstance(value, str):
            match = ENV_PATTERN.fullmatch(value)
            if match:
                key = match.group(1)
                raw = values.get(key, value)
                if key.endswith(("_ENABLED", "_STRICT_MODE", "_LIFECYCLE")) or key in {
                    "E2E_REQUIRE_ARTIFACTS_ENDPOINT",
                    "E2E_REQUIRE_GITHUB_DRAFT_PR",
                    "E2E_REQUIRE_CHECKS",
                }:
                    if raw not in {"true", "false"}:
                        raise ConfigError(
                            f"canonical boolean {key} must be true or false"
                        )
                    return raw == "true"
                if key.endswith(("_GIB", "_TIMEOUT_MS")):
                    try:
                        return int(raw)
                    except ValueError as exc:
                        raise ConfigError(
                            f"canonical integer {key} is invalid"
                        ) from exc
                return raw
            return ENV_PATTERN.sub(
                lambda item: values.get(item.group(1), item.group(0)), value
            )
        return value

    cfg = resolve_config(cfg)
    spec = cfg.get("spec", {})
    host = spec.get("host", {}) if isinstance(spec, dict) else {}
    if isinstance(host, dict):
        for target_key, ref_key in (
            ("ssh", "sshRef"),
            ("root", "rootRef"),
            ("secretsRoot", "secretsRootRef"),
        ):
            ref = str(host.get(ref_key, ""))
            if ref:
                host[target_key] = values[ref]
        excluded_refs = host.get("excludedRefs", [])
        if isinstance(excluded_refs, list):
            host["excluded"] = [values[str(ref)] for ref in excluded_refs]
    if isinstance(spec, dict):
        spec["domain"] = base_domain
        spec["resolvedDomain"] = base_domain
    for component in cfg.get("spec", {}).get("components", []):
        compose = component.get("compose") if isinstance(component, dict) else None
        if compose:
            component["compose"] = "runtime/deploy/" + compose_projection_name(compose)
    cfg["_generated"] = {
        "doNotEdit": True,
        "sourceSha256": source_sha,
        "generatorVersion": GENERATOR_VERSION,
    }
    atomic_text(CONFIG, json.dumps(cfg, indent=2, sort_keys=True) + "\n", 0o600)
    projections.append(projection_row(CONFIG, source_sha))

    manifest = {
        "sourceSha256": source_sha,
        "generatorVersion": GENERATOR_VERSION,
        "projections": sorted(projections, key=lambda row: row["path"]),
    }
    atomic_text(MANIFEST, json.dumps(manifest, indent=2, sort_keys=True) + "\n", 0o600)
    harden_secret_projections(manifest)
    return {
        "rendered": True,
        "sourceSha256": source_sha,
        "generatorVersion": GENERATOR_VERSION,
        "projectionCount": len(projections),
        "manifest": str(MANIFEST),
    }


def drift() -> list[dict[str, str]]:
    values, source_sha = source_state()
    if not MANIFEST.is_file():
        return [{"path": str(MANIFEST), "reason": "manifest_missing"}]
    manifest_stat = MANIFEST.stat()
    if manifest_stat.st_uid != 0 or manifest_stat.st_mode & 0o777 != 0o600:
        return [{"path": str(MANIFEST), "reason": "manifest_permissions"}]
    try:
        manifest = json.loads(MANIFEST.read_text())
    except json.JSONDecodeError:
        return [{"path": str(MANIFEST), "reason": "manifest_invalid"}]
    findings = []
    if manifest.get("sourceSha256") != source_sha:
        findings.append({"path": str(MANIFEST), "reason": "source_hash_drift"})
    if manifest.get("generatorVersion") != GENERATOR_VERSION:
        findings.append({"path": str(MANIFEST), "reason": "generator_version_drift"})
    rows = manifest.get("projections", [])
    if not isinstance(rows, list):
        return [{"path": str(MANIFEST), "reason": "projection_rows_invalid"}]
    plane_rows = [
        row
        for row in rows
        if isinstance(row, dict) and row.get("path") == str(DATA_CONTENT_PLANE)
    ]
    if len(plane_rows) != 1 or set(plane_rows[0]) != {
        "path",
        "contentSha256",
        "sourceSha256",
        "generatorVersion",
    }:
        findings.append(
            {
                "path": str(DATA_CONTENT_PLANE),
                "reason": "projection_manifest_binding_invalid",
            }
        )
    for row in rows:
        if not isinstance(row, dict):
            findings.append({"path": str(MANIFEST), "reason": "projection_row_invalid"})
            continue
        path = Path(str(row.get("path", "")))
        if not path.is_file():
            findings.append({"path": str(path), "reason": "projection_missing"})
            continue
        stat = path.stat()
        if stat.st_uid != 0 or stat.st_mode & 0o777 != 0o600:
            findings.append({"path": str(path), "reason": "projection_permissions"})
        if row.get("sourceSha256") != source_sha:
            findings.append(
                {"path": str(path), "reason": "projection_source_hash_drift"}
            )
        if row.get("generatorVersion") != GENERATOR_VERSION:
            findings.append({"path": str(path), "reason": "projection_generator_drift"})
        if row.get("contentSha256") != sha256_path(path):
            findings.append({"path": str(path), "reason": "projection_content_drift"})
    if DATA_CONTENT_PLANE.is_file():
        try:
            observed = json.loads(DATA_CONTENT_PLANE.read_text())
            resolved_values = dict(values)
            base_domain = (
                resolved_values.get("PLATFORM_BASE_DOMAIN", "").strip().strip(".")
            )
            drift_cfg = active_config_object(
                config_object(), resolved_values, platform_lock_object()
            )
            if base_domain:
                apply_public_projections(drift_cfg, resolved_values, base_domain)
            contract = data_content_contract()
            expected = contract.resolve_from_paths(
                config_object(),
                platform_lock_object(),
                resolved_values,
                config_path=CONFIG_SOURCE,
                lock_path=PLATFORM_LOCK_SOURCE,
                source_sha256=source_sha,
                generator_version=GENERATOR_VERSION,
            )
            if observed != expected:
                findings.append(
                    {
                        "path": str(DATA_CONTENT_PLANE),
                        "reason": "provider_binding_drift",
                    }
                )
        except (OSError, json.JSONDecodeError, ConfigError) as exc:
            findings.append(
                {
                    "path": str(DATA_CONTENT_PLANE),
                    "reason": "provider_binding_invalid",
                    "error": type(exc).__name__,
                }
            )
        except Exception as exc:
            if type(exc).__module__ == "mte_data_content_plane":
                findings.append(
                    {
                        "path": str(DATA_CONTENT_PLANE),
                        "reason": "provider_binding_invalid",
                        "error": type(exc).__name__,
                    }
                )
            else:
                raise
    return findings


def audit() -> dict[str, Any]:
    values, source_sha = source_state()
    cfg = active_config_object(config_object(), values, platform_lock_object())
    required, _, _ = declared_keys(cfg, values)
    missing = missing_required(values, required)
    findings = drift()
    if missing:
        findings.append({"path": str(SOURCE), "reason": "missing_required_keys"})
    result = {
        "ok": not findings,
        "source": str(SOURCE),
        "sourceSha256": source_sha,
        "generatorVersion": GENERATOR_VERSION,
        "missingKeys": missing,
        "findings": findings,
    }
    if findings:
        raise ConfigError(json.dumps(result, sort_keys=True))
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "action",
        choices=("init", "merge-notion-provision", "render", "audit", "diff"),
    )
    parser.add_argument("--expect-idempotent", action="store_true")
    args = parser.parse_args()
    try:
        with config_lock():
            if args.action == "init":
                if args.expect_idempotent:
                    raise ConfigError(
                        "--expect-idempotent requires merge-notion-provision"
                    )
                raw = sys.stdin.read().strip()
                imported = json.loads(raw) if raw else {}
                if not isinstance(imported, dict):
                    raise ConfigError("init input must be a JSON object")
                result = init_source(
                    {str(key): str(value) for key, value in imported.items()}
                )
            elif args.action == "merge-notion-provision":
                raw = sys.stdin.read().strip()
                payload = json.loads(raw) if raw else {}
                if not isinstance(payload, dict):
                    raise ConfigError("notion provision input must be a JSON object")
                result = merge_notion_provision(
                    payload, expect_idempotent=args.expect_idempotent
                )
            elif args.action == "render":
                if args.expect_idempotent:
                    raise ConfigError(
                        "--expect-idempotent requires merge-notion-provision"
                    )
                result = render()
            elif args.action == "audit":
                if args.expect_idempotent:
                    raise ConfigError(
                        "--expect-idempotent requires merge-notion-provision"
                    )
                result = audit()
            else:
                if args.expect_idempotent:
                    raise ConfigError(
                        "--expect-idempotent requires merge-notion-provision"
                    )
                findings = drift()
                result = {"clean": not findings, "findings": findings}
                if findings:
                    print(json.dumps(result, indent=2, sort_keys=True))
                    raise SystemExit(1)
    except ConfigError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, indent=2, sort_keys=True))
        raise SystemExit(1) from exc
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
