name: mte-kestra-data
x-logging: &id001
  driver: json-file
  options:
    max-size: ${MTE_DOCKER_LOG_MAX_SIZE:?required}
    max-file: ${MTE_DOCKER_LOG_MAX_FILES:?required}
services:
  postgres:
    image: ${MTE_KESTRA_DATA_POSTGRES_IMAGE:?required}
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: ${KESTRA_DB_PASSWORD:?required}
    volumes:
    - kestra-postgres:/var/lib/postgresql/data
    networks:
      kestra-data:
        aliases:
        - mte-kestra-postgres
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U kestra -d kestra
      interval: ${MTE_HEALTHCHECK_FAST_INTERVAL:?required}
      timeout: ${MTE_HEALTHCHECK_FAST_TIMEOUT:?required}
      retries: ${MTE_HEALTHCHECK_FAST_RETRIES:?required}
      start_period: ${MTE_HEALTHCHECK_FAST_START_PERIOD:?required}
    restart: unless-stopped
    stop_grace_period: 60s
    cpus: ${KESTRA_DB_CPU_LIMIT:?required}
    mem_limit: ${KESTRA_DB_MEMORY_LIMIT:?required}
    pids_limit: ${MTE_PIDS_DATASTORE_LIMIT:?required}
    logging: *id001
    ports: []
volumes:
  kestra-postgres:
    name: mte-kestra-postgres
networks:
  kestra-data:
    name: mte-kestra-data
