name: mte-postgres
x-logging: &id001
  driver: json-file
  options:
    max-size: ${MTE_DOCKER_LOG_MAX_SIZE:?required}
    max-file: ${MTE_DOCKER_LOG_MAX_FILES:?required}
services:
  postgres:
    image: ${MTE_POSTGRES_POSTGRES_IMAGE:?required}
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:?required}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:?required}
      POSTGRES_DB: ${POSTGRES_ADMIN_DB:?required}
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
      data-plane:
        aliases:
        - mte-postgres
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U ${POSTGRES_ADMIN_USER:?required} -d ${POSTGRES_ADMIN_DB:?required}
      interval: ${MTE_HEALTHCHECK_FAST_INTERVAL:?required}
      timeout: ${MTE_HEALTHCHECK_FAST_TIMEOUT:?required}
      retries: ${MTE_HEALTHCHECK_FAST_RETRIES:?required}
      start_period: ${MTE_HEALTHCHECK_FAST_START_PERIOD:?required}
    restart: unless-stopped
    stop_grace_period: 60s
    cpus: ${POSTGRES_CPU_LIMIT:?required}
    mem_limit: ${POSTGRES_MEMORY_LIMIT:?required}
    pids_limit: ${MTE_PIDS_DATASTORE_LIMIT:?required}
    logging: *id001
    ports: []
volumes:
  postgres-data:
    name: mte-postgres-data
networks:
  data-plane:
    name: mte-data-plane
